### ISSUE TITLE
Why deviate from svelte-icons?

### ISSUE THREAD

**Issue by enyo** [janosh/svicons#2]
Hey! I'm looking for a suitable icon package and was wondering why you decided to create these standalone packages in addition to `svelte-icons`. Could you explain your rationale? (And maybe add it to the README). Thanks.

**Comment by janosh** [comment]
Thanks for your interest. This is still a work in progress. The icon packs should be good to go (I use them in all of my own projects) but the icon explorer (see the [`site/`](https://github.com/janosh/svicons/tree/18989834af862d3c4a9e6e3157a8286eb14d5c4f/site) directory) still has some things to work out.

As for why not contribute to [`svelte-icons`](https://github.com/Introvertuous-Fun/svelte-icons), I wanted to create a 1-to-1 clone for the Svelte ecosystem of the excellent https://styled-icons.dev collections. In fact, I use their explorer site every time I look for a new icon in `svicons`. I remember briefly trying `svelte-icons` but (IIRC) didn't like that it required wrapper divs around icon components just to apply additional styles.

**Comment by janosh** [comment]
We can add the WIP status to the readme. Do you think that would help?

**Comment by enyo** [comment]
Thanks for your answer. So I think it would help to add WIP to the readme, and also add the small paragraph of why you're doing this. It's really hard and time consuming when you're looking for an icon library and you find multiple competing and they don't really describe what their difference is, so that would be very welcome!
